Repository ttpu/SPM24_Final_Project_CosmicBoys, pull requests merged in 2025-01, with the labels that each got.

#8 Update README.md
  README.md
Labels: bug, fix

#12 Abdulbosit
  design/image_2025-01-10_14-30-27.png
  design/photo_2025-01-10_14-30-18.jpg
  design/t
Labels: design

#13 Khojiakbar
  requirements.txt
  src/config/__init__.py
  src/config/__pycache__/__init__.cpython-312.pyc
  src/config/__pycache__/settings.cpython-312.pyc
  src/config/asgi.py
  src/config/settings.py
  src/config/urls.py
  src/config/wsgi.py
  src/manage.py
  src/news/__init__.py
  src/news/admin.py
  src/news/apps.py
  src/news/migrations/__init__.py
  src/news/models.py
  src/news/tests.py
  src/news/views.py
  src/requirements.txt
Labels: back

#26 Khojiakbar
  src/assets/vendor/css/bootstrap.css
  src/assets/vendor/js/bootstrap.bundle.js
  src/config/__pycache__/__init__.cpython-312.pyc
  src/config/__pycache__/settings.cpython-312.pyc
  src/config/__pycache__/urls.cpython-312.pyc
  src/config/__pycache__/wsgi.cpython-312.pyc
  src/config/settings.py
  src/config/urls.py
  src/db.sqlite3
  src/media/news/2022-08-13.png
  src/news/__pycache__/__init__.cpython-312.pyc
  src/news/__pycache__/admin.cpython-312.pyc
  src/news/__pycache__/apps.cpython-312.pyc
  src/news/__pycache__/forms.cpython-312.pyc
  src/news/__pycache__/models.cpython-312.pyc
  src/news/__pycache__/urls.cpython-312.pyc
  src/news/__pycache__/views.cpython-312.pyc
  src/news/admin.py
  src/news/forms.py
  src/news/migrations/0001_initial.py
  src/news/migrations/__pycache__/0001_initial.cpython-312.pyc
  src/news/migrations/__pycache__/__init__.cpython-312.pyc
  src/news/models.py
  src/news/templatetags/__pycache__/filters.cpython-312.pyc
  src/news/templatetags/filters.py
  src/news/urls.py
  src/news/views.py
  src/templates/base.html
Labels: bug, back, authorization

#31 Update and rename Dockerfile.txt to Dockerfile
  Dockerfile
Labels: fix

#34 Update Dockerfile
  Dockerfile
Labels: fix

#35 Update Dockerfile
  Dockerfile
Labels: fix
